name: Disparo WhatsApp via Celular

on:
  push:
    paths:
      - 'trigger.txt' # O fluxo só roda quando você editar este arquivo específico

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install gspread google-auth requests pandas

      - name: Run Disparo
        env:
          EVOLUTION_API_KEY: ${{ secrets.EVOLUTION_API_KEY }}
        run: python main.py
