name: Disparar WhatsApp

on:
  push:
    branches:
      - main  # Dispara toda vez que você der "Push" (salvar) no GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests pandas

      - name: Executar Script de Envio
        run: python main.py
        env:
          API_KEY: ${{ secrets.EVOLUTION_API_KEY }} # Guarde sua chave nos Secrets do GitHub
